# -*- coding: utf-8 -*-
"""Copy of Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuZAfmHa-eB6bK1o4Des3Zm27E_hj5tg
"""

!pip install sentence-transformers faiss-cpu transformers gradio

!pip install transformers accelerate sentencepiece

import pandas as pd

df = pd.read_csv("/content/cars_ds_final.csv")

df.head()

print(df.columns)

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("BAAI/bge-large-en-v1.5")
#print("Embeddings created:", len(embeddings))

texts = []

for _, row in df.iterrows():

    text = f"""
    Car Brand: {row.get('Make', '')}
    Car Model: {row.get('Model', '')}
    Variant: {row.get('Variant', '')}
    Price: {row.get('Ex-Showroom_Price', '')}
    Fuel Type: {row.get('Fuel_Type', '')}
    Body Type: {row.get('Body_Type', '')}
    Mileage: {row.get('City_Mileage', '')}
    Transmission: {row.get('Transmission', '')}
    Seating Capacity: {row.get('Seating_Capacity', '')}
    """

    texts.append(text)

embeddings = model.encode(texts, show_progress_bar=True)

import faiss
import numpy as np

embedding_array = np.array(embeddings).astype('float32')

index = faiss.IndexFlatL2(embedding_array.shape[1])

index.add(embedding_array)
print("FAISS index created with", index.ntotal, "entries")

def retrieve(query, k=5):

    query_embedding = model.encode([query]).astype('float32')

    distances, indices = index.search(query_embedding, k)

    results = []

    for idx in indices[0]:
        results.append(texts[idx])

    return results

retrieve("best mileage car under 10 lakh")

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

def chatbot(query):

    try:

        retrieved_docs = retrieve(query, k=3)

        if not retrieved_docs:
            return "Sorry, I could not find matching cars."

        answer = "## Recommended Cars\n\n"

        for doc in retrieved_docs:

            lines = doc.split("\n")

            brand = "Unknown"
            model_name = "Unknown"
            price = "N/A"
            fuel = "N/A"
            mileage = "N/A"
            body = "N/A"

            for line in lines:

                if "Car Brand:" in line:
                    brand = line.replace("Car Brand:", "").strip()

                elif "Car Model:" in line:
                    model_name = line.replace("Car Model:", "").strip()

                elif "Price:" in line:
                    price = line.replace("Price:", "").strip()

                elif "Fuel Type:" in line:
                    fuel = line.replace("Fuel Type:", "").strip()

                elif "Mileage:" in line:
                    mileage = line.replace("Mileage:", "").strip()

                elif "Body Type:" in line:
                    body = line.replace("Body Type:", "").strip()

            answer += f"""
🚗 {brand} {model_name}

💰 Price: {price}
⛽ Fuel: {fuel}
🛣️ Mileage: {mileage}
🚘 Body Type: {body}

-------------------

"""

        return answer

    except Exception as e:

        return f"Error occurred: {str(e)}"

at

while True:

    query = input("Ask about cars: ")

    if query.lower() == "exit":
        break

    response = chatbot(query)

    print("\nAnswer:\n")
    print(response)
    print("\n" + "="*60 + "\n")